const { constants: { MINIAPP, WECHAT_MINIPROGRAM, BYTEDANCE_MICROAPP, BAIDU_SMARTPROGRAM, KUAISHOU_MINIPROGRAM, QUICKAPP } } = require('miniapp-builder-shared');

module.exports = {
  WEB: 'web',
  DOCUMENT: 'document',
  SSR: 'ssr',
  WEEX: 'weex',
  KRAKEN: 'kraken',
  HARMONY: 'harmony',
  MINIAPP,
  WECHAT_MINIPROGRAM,
  BYTEDANCE_MICROAPP,
  BAIDU_SMARTPROGRAM,
  KUAISHOU_MINIPROGRAM,
  QUICKAPP,
  MINIAPP_PLATFORMS: [MINIAPP, WECHAT_MINIPROGRAM, BYTEDANCE_MICROAPP, BAIDU_SMARTPROGRAM, KUAISHOU_MINIPROGRAM],
  GET_RAX_APP_WEBPACK_CONFIG: 'getRaxAppWebpackConfig',
  DEV_URL_PREFIX: 'devUrlPrefix',
  STATIC_CONFIG: 'staticConfig',
  TAB_BAR_PATH: 'TAB_BAR_PATH',
  REACT_TRANSFORM_CONFIG: 'REACT_TRANSFORM_CONFIG',
  MINIFY_TASKS: 'MINIFY_TASKS',
  DEPRECATED_CONFIG: {
    esbuild: 'esbuild',
    terserOptions: 'terser',
  },
  HTTPS_URL_LIST: 'HTTPS_URL_LIST',
};
