module.exports = {
  WEB: 'web',
  DOCUMENT: 'document',
  SSR: 'ssr',
  WEEX: 'weex',
  KRAKEN: 'kraken',
  MINIAPP: 'miniapp',
  WECHAT_MINIPROGRAM: 'wechat-miniprogram',
  BYTEDANCE_MICROAPP: 'bytedance-microapp',
  QUICKAPP: 'quickapp',
  GET_RAX_APP_WEBPACK_CONFIG: 'getRaxAppWebpackConfig',
  DEV_URL_PREFIX: 'devUrlPrefix',
  STATIC_CONFIG: 'staticConfig',
  CUSTOM_TAB_BAR: 'CUSTOM_TAB_BAR',
};
