// appConfig keys need transform to manifest
const manifestRetainKeys = [
  'name',
  'startUrl',
  'shortName',
  'lang',
  'dir',
  'description',
  'backgroundColor',
  'display',
  'icons',
  'appWorker',
  'window',
  'pageHeader',
  'tabHeader',
  'tabBar',
  'pages',
  'dataPrefetch',
  'spm',
  'metas',
  'links',
  'scripts',
  'offlineResources',
  'packageResources',
  'manifestPrefetchExpires',
  'manifestPrefetchMaxAge',
  'maxAge',
  'expires',
  'queryParamsPassKeys',
  'queryParamsPassIgnoreKeys',
  'splashViewTimeout',
  'splashViewAutoClose',
  'splashViewHtml',
  'splashViewUrl',
  'swiperThreshold',
  'requestHeaders',
  'enablePoplayer',
  'disableCapture',
  'enablePullRefresh',
  'pullRefreshBackgroundColor',
  'pullRefreshColorScheme',
  'pullRefresh',
  'cacheQueryParams',
];

// do not decamelize list
const manifestCamelizeKeys = [
  'appKey',
  'dataType',
  'valueType',
  'isSec',
  'LoginRequest',
  'sessionOption',
  'AntiCreep',
  'AntiFlood',
  'needLogin',
];

module.exports = {
  manifestRetainKeys,
  manifestCamelizeKeys,
};
